# Generated by Django 5.0.7 on 2024-07-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
            options={
                'unique_together': {('model_name', 'data')},
            },
        ),
    ]
