# Generated by Django 5.0.7 on 2024-07-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dynamicmodel',
            unique_together=set(),
        ),
    ]
